#!/usr/bin/env python

from beetsplug.ydl import Colors
import os
import subprocess
from hashlib import md5

#
# To get a checksum: leave the first field blank, put an URL in the
# second field, and then run the test
#
TESTS = [
    ('4e4372f5d09d872b69654c81620bf6ac', 'https://www.youtube.com/watch?v=uMMUcxvWOkY'),
    ('af029d7b149e119f5a527440acf2e748', 'https://www.youtube.com/watch?v=Zi_XLOBDo_Y'),
    ('ec734593c0a61678f8a9399f1325d180', 'https://www.youtube.com/watch?v=wW6ykueIhX8'),
]

dbfile = 'env.lib.db'
ydl_cmd = ['beet', '-c', 'env.config.yml', '-l', dbfile, 'ydl', '--no-download',
    '--no-import', '--verbose']

# so no cache messages will appear
if os.path.exists(dbfile):
    os.remove(dbfile)

failed = False

for checksum, source in TESTS:
    cmd = ydl_cmd + [source]
    print(Colors.INFO + '=> ' + Colors.END + \
        Colors.BOLD + ' '.join(cmd) + Colors.END)
    result = subprocess.run(cmd, stdout=subprocess.PIPE)
    md5_result = md5(str(result.stdout).encode()).hexdigest()

    if checksum and md5_result == checksum:
        output = Colors.SUCCESS + "   [OK] " + Colors.END + md5_result
    elif checksum:
        output = Colors.WARNING + "   [ERROR] " + Colors.END + \
            md5_result + " <> " + checksum
        failed = True
    else:
        output = Colors.INFO + "   [CHECKSUM] " + md5_result + Colors.END
        print(result.stdout.decode("unicode_escape"))
    print(output)

if failed:
    exit(2)
else:
    exit(0)